server: ftp.ncbi.nih.gov
bucket: czbiohub-ncbi-store

syncFolders:
  - name: /blast/db/FASTA
    flags:
      - include '*/'
      - include 'n?.gz'
      - exclude '*'
  - name: /pub/taxonomy
    flags:
      - exclude '.*'
      - include '*/'
      - include 'accession2taxid/*'
      - include 'taxdump.tar.gz'
      - exclude '*'
